"""initial schema

Revision ID: f6f6706f024d
Revises:
Create Date: 2026-07-18 17:37:36.664540
"""

from collections.abc import Sequence
from typing import Optional, Union

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

revision: str = "f6f6706f024d"
down_revision: Optional[str] = None
branch_labels: Optional[Union[str, Sequence[str]]] = None
depends_on: Optional[Union[str, Sequence[str]]] = None


APPEND_ONLY_TABLES = (
    "conversation_messages",
    "triage_answers",
    "safety_flags",
    "staff_decisions",
    "audit_logs",
)


def _create_append_only_triggers() -> None:
    """PostgreSQL-only: block UPDATE/DELETE on append-only tables at the DB level.

    On other dialects (e.g. SQLite used for local verification) the
    repository-port layer is the enforcement boundary — ports for these
    tables expose no update/delete operations.
    """
    if op.get_bind().dialect.name != "postgresql":
        return
    op.execute(
        """
        CREATE OR REPLACE FUNCTION careflow_block_mutation()
        RETURNS TRIGGER AS $$
        BEGIN
            RAISE EXCEPTION 'Table % is append-only', TG_TABLE_NAME;
        END;
        $$ LANGUAGE plpgsql;
        """
    )
    for table in APPEND_ONLY_TABLES:
        op.execute(
            f"""
            CREATE TRIGGER trg_{table}_append_only
            BEFORE UPDATE OR DELETE ON {table}
            FOR EACH ROW EXECUTE FUNCTION careflow_block_mutation();
            """
        )


def _drop_append_only_triggers() -> None:
    if op.get_bind().dialect.name != "postgresql":
        return
    for table in APPEND_ONLY_TABLES:
        op.execute(f"DROP TRIGGER IF EXISTS trg_{table}_append_only ON {table};")
    op.execute("DROP FUNCTION IF EXISTS careflow_block_mutation();")


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "staff_users",
        sa.Column("staff_user_id", sa.Uuid(), nullable=False),
        sa.Column("email", sa.String(length=255), nullable=False),
        sa.Column(
            "role",
            sa.Enum(
                "triage_nurse",
                "administrator",
                "supervisor",
                name="staff_role",
                native_enum=False,
                length=50,
            ),
            nullable=False,
        ),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("staff_user_id"),
        sa.UniqueConstraint("email"),
    )
    op.create_index("ix_staff_users_role", "staff_users", ["role"], unique=False)
    op.create_table(
        "user_sessions",
        sa.Column("session_id", sa.Uuid(), nullable=False),
        sa.Column(
            "language",
            sa.Enum("en", "ar", name="language", native_enum=False, length=50),
            nullable=False,
        ),
        sa.Column("is_authenticated", sa.Boolean(), nullable=False),
        sa.Column("staff_user_id", sa.Uuid(), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["staff_user_id"], ["staff_users.staff_user_id"], ondelete="SET NULL"
        ),
        sa.PrimaryKeyConstraint("session_id"),
    )
    op.create_index("ix_user_sessions_created_at", "user_sessions", ["created_at"], unique=False)
    op.create_index(
        "ix_user_sessions_staff_user_id", "user_sessions", ["staff_user_id"], unique=False
    )
    op.create_table(
        "service_requests",
        sa.Column("request_id", sa.Uuid(), nullable=False),
        sa.Column("session_id", sa.Uuid(), nullable=False),
        sa.Column("initial_description", sa.Text(), nullable=False),
        sa.Column(
            "language",
            sa.Enum("en", "ar", name="request_language", native_enum=False, length=50),
            nullable=False,
        ),
        sa.Column(
            "status",
            sa.Enum(
                "pending",
                "intake_complete",
                "in_triage",
                "triage_complete",
                "safety_alert",
                "awaiting_recommendation",
                "recommendation_ready",
                "staff_review",
                "closed",
                name="request_status",
                native_enum=False,
                length=50,
            ),
            nullable=False,
        ),
        sa.Column(
            "classification",
            sa.Enum(
                "administrative",
                "healthcare",
                "unclear",
                name="request_classification",
                native_enum=False,
                length=50,
            ),
            nullable=True,
        ),
        sa.Column(
            "urgency_level",
            sa.Enum(
                "low",
                "medium",
                "high",
                "emergency",
                name="urgency_level",
                native_enum=False,
                length=50,
            ),
            nullable=True,
        ),
        sa.Column(
            "recommended_service",
            sa.Enum(
                "administrative_service",
                "virtual_consultation",
                "primary_care",
                "urgent_care",
                "emergency_department",
                "human_review",
                name="recommended_service",
                native_enum=False,
                length=50,
            ),
            nullable=True,
        ),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("completed_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(["session_id"], ["user_sessions.session_id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("request_id"),
    )
    op.create_index(
        "ix_service_requests_created_at", "service_requests", ["created_at"], unique=False
    )
    op.create_index(
        "ix_service_requests_session_id", "service_requests", ["session_id"], unique=False
    )
    op.create_index("ix_service_requests_status", "service_requests", ["status"], unique=False)
    op.create_table(
        "ai_recommendations",
        sa.Column("recommendation_id", sa.Uuid(), nullable=False),
        sa.Column("request_id", sa.Uuid(), nullable=False),
        sa.Column(
            "recommended_service",
            sa.Enum(
                "administrative_service",
                "virtual_consultation",
                "primary_care",
                "urgent_care",
                "emergency_department",
                "human_review",
                name="rec_recommended_service",
                native_enum=False,
                length=50,
            ),
            nullable=False,
        ),
        sa.Column(
            "urgency_level",
            sa.Enum(
                "low",
                "medium",
                "high",
                "emergency",
                name="rec_urgency_level",
                native_enum=False,
                length=50,
            ),
            nullable=False,
        ),
        sa.Column("rationale", sa.Text(), nullable=False),
        sa.Column("confidence", sa.Float(), nullable=False),
        sa.Column("confidence_reason", sa.Text(), nullable=False),
        sa.Column("rule_triggered", sa.String(length=100), nullable=True),
        sa.Column("model_provider", sa.String(length=50), nullable=False),
        sa.Column("model_name", sa.String(length=100), nullable=False),
        sa.Column("prompt_version", sa.String(length=20), nullable=False),
        sa.Column("workflow_version", sa.String(length=20), nullable=False),
        sa.Column("schema_version", sa.String(length=20), nullable=False),
        sa.Column("generated_at", sa.DateTime(timezone=True), nullable=False),
        sa.CheckConstraint(
            "confidence >= 0.0 AND confidence <= 1.0", name="ck_recommendations_confidence"
        ),
        sa.ForeignKeyConstraint(
            ["request_id"], ["service_requests.request_id"], ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("recommendation_id"),
        sa.UniqueConstraint("request_id"),
    )
    op.create_index(
        "ix_ai_recommendations_generated_at", "ai_recommendations", ["generated_at"], unique=False
    )
    op.create_table(
        "audit_logs",
        sa.Column("log_id", sa.Uuid(), nullable=False),
        sa.Column("request_id", sa.Uuid(), nullable=False),
        sa.Column("actor", sa.String(length=100), nullable=False),
        sa.Column("action", sa.String(length=100), nullable=False),
        sa.Column(
            "details",
            sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), "postgresql"),
            nullable=True,
        ),
        sa.Column("model_provider", sa.String(length=50), nullable=True),
        sa.Column("model_name", sa.String(length=100), nullable=True),
        sa.Column("prompt_version", sa.String(length=20), nullable=True),
        sa.Column("workflow_version", sa.String(length=20), nullable=True),
        sa.Column("schema_version", sa.String(length=20), nullable=True),
        sa.Column("logged_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["request_id"], ["service_requests.request_id"], ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("log_id"),
    )
    op.create_index("ix_audit_logs_action", "audit_logs", ["action"], unique=False)
    op.create_index("ix_audit_logs_logged_at", "audit_logs", ["logged_at"], unique=False)
    op.create_index("ix_audit_logs_request_id", "audit_logs", ["request_id"], unique=False)
    op.create_table(
        "conversation_messages",
        sa.Column("message_id", sa.Uuid(), nullable=False),
        sa.Column("request_id", sa.Uuid(), nullable=False),
        sa.Column("role", sa.String(length=20), nullable=False),
        sa.Column("content", sa.Text(), nullable=False),
        sa.Column("message_type", sa.String(length=50), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.CheckConstraint("role IN ('user', 'assistant', 'system')", name="ck_messages_role"),
        sa.ForeignKeyConstraint(
            ["request_id"], ["service_requests.request_id"], ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("message_id"),
    )
    op.create_index(
        "ix_conversation_messages_created_at", "conversation_messages", ["created_at"], unique=False
    )
    op.create_index(
        "ix_conversation_messages_request_id", "conversation_messages", ["request_id"], unique=False
    )
    op.create_table(
        "safety_flags",
        sa.Column("flag_id", sa.Uuid(), nullable=False),
        sa.Column("request_id", sa.Uuid(), nullable=False),
        sa.Column("rule_code", sa.String(length=100), nullable=False),
        sa.Column(
            "severity",
            sa.Enum(
                "info",
                "warning",
                "critical",
                name="safety_flag_severity",
                native_enum=False,
                length=50,
            ),
            nullable=False,
        ),
        sa.Column("description", sa.Text(), nullable=False),
        sa.Column("action_taken", sa.String(length=100), nullable=False),
        sa.Column("triggered_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["request_id"], ["service_requests.request_id"], ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("flag_id"),
    )
    op.create_index("ix_safety_flags_request_id", "safety_flags", ["request_id"], unique=False)
    op.create_index("ix_safety_flags_rule_code", "safety_flags", ["rule_code"], unique=False)
    op.create_index("ix_safety_flags_severity", "safety_flags", ["severity"], unique=False)
    op.create_table(
        "staff_decisions",
        sa.Column("decision_id", sa.Uuid(), nullable=False),
        sa.Column("request_id", sa.Uuid(), nullable=False),
        sa.Column("staff_user_id", sa.Uuid(), nullable=False),
        sa.Column(
            "decision_type",
            sa.Enum(
                "accept",
                "modify",
                "escalate",
                "close",
                "refer",
                name="staff_decision_type",
                native_enum=False,
                length=50,
            ),
            nullable=False,
        ),
        sa.Column("notes", sa.Text(), nullable=True),
        sa.Column(
            "modified_service",
            sa.Enum(
                "administrative_service",
                "virtual_consultation",
                "primary_care",
                "urgent_care",
                "emergency_department",
                "human_review",
                name="decision_modified_service",
                native_enum=False,
                length=50,
            ),
            nullable=True,
        ),
        sa.Column(
            "modified_urgency",
            sa.Enum(
                "low",
                "medium",
                "high",
                "emergency",
                name="decision_modified_urgency",
                native_enum=False,
                length=50,
            ),
            nullable=True,
        ),
        sa.Column("reason", sa.Text(), nullable=True),
        sa.Column("decided_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["request_id"], ["service_requests.request_id"], ondelete="CASCADE"
        ),
        sa.ForeignKeyConstraint(
            ["staff_user_id"], ["staff_users.staff_user_id"], ondelete="RESTRICT"
        ),
        sa.PrimaryKeyConstraint("decision_id"),
    )
    op.create_index(
        "ix_staff_decisions_decided_at", "staff_decisions", ["decided_at"], unique=False
    )
    op.create_index(
        "ix_staff_decisions_request_id", "staff_decisions", ["request_id"], unique=False
    )
    op.create_index(
        "ix_staff_decisions_staff_user_id", "staff_decisions", ["staff_user_id"], unique=False
    )
    op.create_table(
        "triage_answers",
        sa.Column("answer_id", sa.Uuid(), nullable=False),
        sa.Column("request_id", sa.Uuid(), nullable=False),
        sa.Column("question_id", sa.String(length=100), nullable=False),
        sa.Column("question_text", sa.Text(), nullable=False),
        sa.Column("user_answer", sa.Text(), nullable=False),
        sa.Column("processed_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["request_id"], ["service_requests.request_id"], ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("answer_id"),
        sa.UniqueConstraint("request_id", "question_id", name="uq_triage_answers_request_question"),
    )
    op.create_index("ix_triage_answers_request_id", "triage_answers", ["request_id"], unique=False)
    # ### end Alembic commands ###

    _create_append_only_triggers()


def downgrade() -> None:
    _drop_append_only_triggers()
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("ix_triage_answers_request_id", table_name="triage_answers")
    op.drop_table("triage_answers")
    op.drop_index("ix_staff_decisions_staff_user_id", table_name="staff_decisions")
    op.drop_index("ix_staff_decisions_request_id", table_name="staff_decisions")
    op.drop_index("ix_staff_decisions_decided_at", table_name="staff_decisions")
    op.drop_table("staff_decisions")
    op.drop_index("ix_safety_flags_severity", table_name="safety_flags")
    op.drop_index("ix_safety_flags_rule_code", table_name="safety_flags")
    op.drop_index("ix_safety_flags_request_id", table_name="safety_flags")
    op.drop_table("safety_flags")
    op.drop_index("ix_conversation_messages_request_id", table_name="conversation_messages")
    op.drop_index("ix_conversation_messages_created_at", table_name="conversation_messages")
    op.drop_table("conversation_messages")
    op.drop_index("ix_audit_logs_request_id", table_name="audit_logs")
    op.drop_index("ix_audit_logs_logged_at", table_name="audit_logs")
    op.drop_index("ix_audit_logs_action", table_name="audit_logs")
    op.drop_table("audit_logs")
    op.drop_index("ix_ai_recommendations_generated_at", table_name="ai_recommendations")
    op.drop_table("ai_recommendations")
    op.drop_index("ix_service_requests_status", table_name="service_requests")
    op.drop_index("ix_service_requests_session_id", table_name="service_requests")
    op.drop_index("ix_service_requests_created_at", table_name="service_requests")
    op.drop_table("service_requests")
    op.drop_index("ix_user_sessions_staff_user_id", table_name="user_sessions")
    op.drop_index("ix_user_sessions_created_at", table_name="user_sessions")
    op.drop_table("user_sessions")
    op.drop_index("ix_staff_users_role", table_name="staff_users")
    op.drop_table("staff_users")
    # ### end Alembic commands ###
